### PR TITLE
fix: fix #128

### LINKED ISSUE #128: JOSE Header with `typ` set to `JWT` fails
Per https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.9:

> The "typ" (type) Header Parameter is used by JWS applications to
   declare the media type [IANA.MediaTypes] of this complete JWS.
but
> To keep messages compact in common situations, it is RECOMMENDED that
   producers omit an "application/" prefix of a media type value in a
   "typ" Header Parameter when no other '/' appears in the media type
   value.

So while a JSON Web Token has the media type `application/jwt` (also must ignore case and it is recommended to be uppercase)
> While
   media type names are not case sensitive, it is RECOMMENDED that "JWT"
   always be spelled using uppercase characters for compatibility with
   legacy implementations. 

it will only be set to `jwt` OR `JWT` which both are valid but our implementation fails, because https://docs.rs/mediatype/0.19.20/mediatype/struct.MediaTypeBuf.html#method.from_string cannot handle this "non standard" mediatype.

The simple fix is to add a special check and set the mediatype manually AND also add a note in the docs. We also should adjust serialization to only serialize `JWT`.

### PR DESCRIPTION
**Pull request by Erik1000**

### CODE REVIEW

File: src/header/parameters.rs [hunk 1]
```diff
@@ -33,12 +35,98 @@ pub(crate) struct Parameters<T> {
...
+impl Serialize for MediaTypeWithMaybeStrippedApplicationTopLevel {
+    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
+    where
+        S: serde::Serializer,
+    {
+        let correct = self.0.to_string();
+        if self.0.ty() == mediatype::names::APPLICATION
+            && correct.chars().filter(|c| *c == '/').count() == 1
+        {
+            let raw = correct.split_once('/').expect("contains one slash").1;
```
Comment (Stupremee) [inline src/header/parameters.rs:91]: Can't you use the `MediaTypeBuf.subty` field so you don't have to do the parsing by yourself?

File: src/header/parameters.rs [hunk 2]
```diff
@@ -33,12 +35,98 @@ pub(crate) struct Parameters<T> {
...
+#[derive(Debug)]
+pub(crate) struct MediaTypeWithMaybeStrippedApplicationTopLevel(pub(crate) MediaTypeBuf);
+
+impl<'de> Deserialize<'de> for MediaTypeWithMaybeStrippedApplicationTopLevel {
+    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
+    where
+        D: serde::Deserializer<'de>,
+    {
+        let raw: Cow<'_, str> = Cow::deserialize(deserializer)?;
+        let corrected = if raw.find("/").is_none() {
```
Comment (Stupremee) [inline src/header/parameters.rs:72]: Use `raw.contains('/')` which should be a bit more optimized

**Review by Stupremee — CHANGES_REQUESTED** [review]

**Review by Stupremee — APPROVED** [review]
